import type {
  ActivityLog,
  Banner,
  Booking,
  Business,
  Category,
  Enquiry,
  OperatingHours,
  Plan,
  PlatformSettings,
  Product,
  Review,
  Service,
  Subscription,
  Town,
  UserProfile
} from "@/types";
import { planDefinitions } from "@/constants/plans";
import { SUPPORTED_PAYMENT_PROVIDERS } from "@/constants/platform";

const timestamp = "2026-03-29T08:00:00.000Z";

const weekdayHours: OperatingHours = {
  monday: { open: "08:00", close: "17:00", closed: false },
  tuesday: { open: "08:00", close: "17:00", closed: false },
  wednesday: { open: "08:00", close: "17:00", closed: false },
  thursday: { open: "08:00", close: "17:00", closed: false },
  friday: { open: "08:00", close: "17:00", closed: false },
  saturday: { open: "08:00", close: "13:00", closed: false },
  sunday: { open: "00:00", close: "00:00", closed: true }
};

const hospitalityHours: OperatingHours = {
  monday: { open: "07:00", close: "21:00", closed: false },
  tuesday: { open: "07:00", close: "21:00", closed: false },
  wednesday: { open: "07:00", close: "21:00", closed: false },
  thursday: { open: "07:00", close: "21:00", closed: false },
  friday: { open: "07:00", close: "22:00", closed: false },
  saturday: { open: "08:00", close: "22:00", closed: false },
  sunday: { open: "08:00", close: "16:00", closed: false }
};

export const towns: Town[] = [
  {
    id: "town-vryheid",
    name: "Vryheid",
    slug: "vryheid",
    province: "KwaZulu-Natal",
    country: "South Africa",
    isActive: true,
    heroImageUrl:
      "https://images.unsplash.com/photo-1519583272095-6433daf26b6e?auto=format&fit=crop&w=1400&q=80",
    createdAt: timestamp,
    updatedAt: timestamp
  }
];

export const categories: Category[] = [
  ["Restaurants", "utensils-crossed", "Places to eat, caterers, takeaways and local food brands."],
  ["Beauty", "sparkles", "Salons, barbers, nail studios and beauty professionals."],
  ["Construction", "hammer", "Building, renovations, contractors and project services."],
  ["Plumbing", "wrench", "Plumbers, maintenance and urgent repair specialists."],
  ["Electrical", "zap", "Electricians, installations and power solutions."],
  ["Events", "party-popper", "Decor, hire, entertainment and event execution teams."],
  ["Fashion", "shirt", "Boutiques, designers, tailoring and custom apparel."],
  ["Printing", "printer", "Print shops, signage, stationery and branded materials."],
  ["Car Services", "car", "Mechanics, panel beaters, detailing and tyre support."],
  ["Health", "heart-pulse", "Clinics, wellness, therapy and allied health services."],
  ["Education", "graduation-cap", "Tutors, training centres and after-school learning."],
  ["Agriculture", "leaf", "Farm support, suppliers and agri-services."],
  ["Accommodation", "bed", "Guest houses, B&Bs and short-stay bookings."],
  ["Professional Services", "briefcase-business", "Consulting, finance, legal and office services."]
].map(([name, icon, description], index) => ({
  id: `category-${name.toLowerCase().replace(/\s+/g, "-")}`,
  name,
  slug: name.toLowerCase().replace(/\s+/g, "-"),
  icon,
  description,
  isActive: true,
  sortOrder: index + 1,
  createdAt: timestamp,
  updatedAt: timestamp
}));

export const users: UserProfile[] = [
  {
    id: "user-admin",
    fullName: "TownConnect Admin",
    email: "admin@townconnect.co.za",
    phone: "+27830000001",
    whatsappNumber: "+27830000001",
    role: "admin",
    profileImage: "",
    townId: "town-vryheid",
    province: "KwaZulu-Natal",
    referralCode: "ADMIN-HQ",
    signupSource: "organic",
    onboardingStatus: "admin_assisted",
    createdAt: timestamp,
    updatedAt: timestamp,
    isActive: true
  },
  {
    id: "user-customer",
    fullName: "Lerato Mthembu",
    email: "customer@townconnect.co.za",
    phone: "+27830000002",
    whatsappNumber: "+27830000002",
    role: "customer",
    profileImage: "",
    townId: "town-vryheid",
    province: "KwaZulu-Natal",
    referralCode: "LERATO-REF",
    signupSource: "referral",
    referredByCode: "VRY-NEIGHBOUR",
    onboardingStatus: "self_signup",
    createdAt: timestamp,
    updatedAt: timestamp,
    isActive: true
  },
  {
    id: "user-owner-food",
    fullName: "Siyabonga Khumalo",
    email: "owner@townconnect.co.za",
    phone: "+27830000003",
    whatsappNumber: "+27830000003",
    role: "business_owner",
    profileImage: "",
    townId: "town-vryheid",
    province: "KwaZulu-Natal",
    referralCode: "OWNER-FOOD",
    agentId: "agent-kzn-001",
    signupSource: "agent",
    onboardingStatus: "agent_assisted",
    createdAt: timestamp,
    updatedAt: timestamp,
    isActive: true
  },
  {
    id: "user-owner-beauty",
    fullName: "Nomfundo Dlamini",
    email: "beauty@townconnect.co.za",
    phone: "+27830000004",
    whatsappNumber: "+27830000004",
    role: "business_owner",
    profileImage: "",
    townId: "town-vryheid",
    province: "KwaZulu-Natal",
    referralCode: "OWNER-BEAUTY",
    agentId: "agent-kzn-002",
    signupSource: "agent",
    onboardingStatus: "agent_assisted",
    createdAt: timestamp,
    updatedAt: timestamp,
    isActive: true
  },
  {
    id: "user-owner-trade",
    fullName: "Sibusiso Ndlovu",
    email: "trade@townconnect.co.za",
    phone: "+27830000005",
    whatsappNumber: "+27830000005",
    role: "business_owner",
    profileImage: "",
    townId: "town-vryheid",
    province: "KwaZulu-Natal",
    referralCode: "OWNER-TRADE",
    agentId: "agent-kzn-001",
    signupSource: "referral",
    onboardingStatus: "agent_assisted",
    createdAt: timestamp,
    updatedAt: timestamp,
    isActive: true
  }
];

export const businesses: Business[] = [
  {
    id: "business-vryheid-grill-house",
    ownerId: "user-owner-food",
    businessName: "Vryheid Grill House",
    slug: "vryheid-grill-house",
    description:
      "A family-friendly grill and takeaway spot serving flame-grilled favourites, kota combos and event platters for Vryheid locals.",
    shortDescription: "Local grill house, takeaways and catering platters.",
    logoUrl:
      "https://images.unsplash.com/photo-1552566626-52f8b828add9?auto=format&fit=crop&w=400&q=80",
    coverImageUrl:
      "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=1400&q=80",
    galleryUrls: [
      "https://images.unsplash.com/photo-1550547660-d9450f859349?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1551782450-a2132b4ba21d?auto=format&fit=crop&w=800&q=80"
    ],
    categoryId: "category-restaurants",
    subcategory: "Grill & Takeaway",
    tags: ["burgers", "platters", "catering", "takeaway"],
    phone: "+27831230001",
    whatsappNumber: "+27831230001",
    email: "hello@grillhouse.co.za",
    website: "",
    socialLinks: {
      facebook: "https://facebook.com/vryheidgrillhouse",
      instagram: "https://instagram.com/vryheidgrillhouse"
    },
    addressLine1: "88 Church Street",
    addressLine2: "",
    suburb: "Vryheid Central",
    townId: "town-vryheid",
    province: "KwaZulu-Natal",
    country: "South Africa",
    geo: { lat: -27.7696, lng: 30.7916 },
    servicesEnabled: true,
    productsEnabled: true,
    bookingsEnabled: true,
    paymentsEnabled: false,
    deliveryEnabled: true,
    pickupEnabled: true,
    operatingHours: hospitalityHours,
    priceRange: "R",
    verificationStatus: "verified",
    listingStatus: "active",
    featured: true,
    featuredUntil: "2026-06-30T00:00:00.000Z",
    leadFlowType: "whatsapp_first",
    allowInstantWhatsAppLead: true,
    whatsappPrefillTemplate: "Hi, I found your business on TownConnect and want to enquire about your menu or catering options.",
    sponsoredStatus: "eligible",
    priorityScore: 20,
    agentId: "agent-kzn-001",
    referralCode: "GRILL-VRY-01",
    onboardingSource: "agent",
    paymentProviderPreference: "placeholder",
    averageRating: 4.6,
    reviewCount: 28,
    subscriptionPlanId: "plan-standard",
    subscriptionStatus: "active",
    viewsCount: 1624,
    enquiriesCount: 94,
    bookingsCount: 37,
    createdAt: timestamp,
    updatedAt: timestamp
  },
  {
    id: "business-glow-beauty-studio",
    ownerId: "user-owner-beauty",
    businessName: "Glow Beauty Studio",
    slug: "glow-beauty-studio",
    description:
      "Beauty treatments, nails, lashes and makeup appointments with online bookings for busy professionals, students and bridal clients.",
    shortDescription: "Beauty studio for nails, lashes and makeup.",
    logoUrl:
      "https://images.unsplash.com/photo-1522337660859-02fbefca4702?auto=format&fit=crop&w=400&q=80",
    coverImageUrl:
      "https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?auto=format&fit=crop&w=1400&q=80",
    galleryUrls: [
      "https://images.unsplash.com/photo-1604654894610-df63bc536371?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1616394584738-fc6e612e71b9?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1596704017254-9753ee57a5aa?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1512496015851-a90fb38ba796?auto=format&fit=crop&w=800&q=80"
    ],
    categoryId: "category-beauty",
    subcategory: "Beauty Studio",
    tags: ["lashes", "nails", "makeup", "bridal"],
    phone: "+27831230002",
    whatsappNumber: "+27831230002",
    email: "bookings@glowbeauty.co.za",
    website: "",
    socialLinks: {
      instagram: "https://instagram.com/glowbeautyvryheid",
      tiktok: "https://tiktok.com/@glowbeautyvryheid"
    },
    addressLine1: "14 Hoog Street",
    addressLine2: "Suite 3",
    suburb: "Vryheid Central",
    townId: "town-vryheid",
    province: "KwaZulu-Natal",
    country: "South Africa",
    geo: { lat: -27.7715, lng: 30.7911 },
    servicesEnabled: true,
    productsEnabled: true,
    bookingsEnabled: true,
    paymentsEnabled: false,
    deliveryEnabled: false,
    pickupEnabled: false,
    operatingHours: weekdayHours,
    priceRange: "R-RR",
    verificationStatus: "verified",
    listingStatus: "active",
    featured: true,
    featuredUntil: "2026-07-15T00:00:00.000Z",
    leadFlowType: "whatsapp_first",
    allowInstantWhatsAppLead: true,
    whatsappPrefillTemplate: "Hi, I found Glow Beauty Studio on TownConnect and want to book a treatment.",
    sponsoredStatus: "active",
    sponsoredPlacement: "home_feature",
    sponsoredUntil: "2026-07-15T00:00:00.000Z",
    sponsoredCampaignId: "campaign-premium-glow-q2",
    priorityScore: 40,
    bannerCreditsUsed: 1,
    agentId: "agent-kzn-002",
    referralCode: "GLOW-VRY-01",
    onboardingSource: "agent",
    paymentProviderPreference: "placeholder",
    averageRating: 4.8,
    reviewCount: 51,
    subscriptionPlanId: "plan-premium",
    subscriptionStatus: "active",
    viewsCount: 2311,
    enquiriesCount: 126,
    bookingsCount: 83,
    createdAt: timestamp,
    updatedAt: timestamp
  },
  {
    id: "business-amajuba-buildworks",
    ownerId: "user-owner-trade",
    businessName: "Amajuba BuildWorks",
    slug: "amajuba-buildworks",
    description:
      "Residential building, renovations and site supervision with a strong footprint in Vryheid and surrounding farming areas.",
    shortDescription: "Construction, renovations and project support.",
    logoUrl:
      "https://images.unsplash.com/photo-1504307651254-35680f356dfd?auto=format&fit=crop&w=400&q=80",
    coverImageUrl:
      "https://images.unsplash.com/photo-1503387762-592deb58ef4e?auto=format&fit=crop&w=1400&q=80",
    galleryUrls: [
      "https://images.unsplash.com/photo-1489515217757-5fd1be406fef?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1541888946425-d81bb19240f5?auto=format&fit=crop&w=800&q=80"
    ],
    categoryId: "category-construction",
    subcategory: "Building Contractor",
    tags: ["renovations", "roofing", "brickwork", "projects"],
    phone: "+27831230003",
    whatsappNumber: "+27831230003",
    email: "projects@buildworks.co.za",
    website: "",
    socialLinks: {
      facebook: "https://facebook.com/amajubabuildworks"
    },
    addressLine1: "21 Mason Road",
    addressLine2: "",
    suburb: "Lakeside",
    townId: "town-vryheid",
    province: "KwaZulu-Natal",
    country: "South Africa",
    geo: { lat: -27.7664, lng: 30.8001 },
    servicesEnabled: true,
    productsEnabled: false,
    bookingsEnabled: true,
    paymentsEnabled: false,
    deliveryEnabled: false,
    pickupEnabled: false,
    operatingHours: weekdayHours,
    priceRange: "RR",
    verificationStatus: "verified",
    listingStatus: "active",
    featured: false,
    featuredUntil: "",
    leadFlowType: "hybrid",
    allowInstantWhatsAppLead: true,
    whatsappPrefillTemplate: "Hi, I found Amajuba BuildWorks on TownConnect and need a quote.",
    sponsoredStatus: "eligible",
    priorityScore: 18,
    agentId: "agent-kzn-001",
    referralCode: "BUILD-VRY-01",
    onboardingSource: "agent",
    averageRating: 4.4,
    reviewCount: 17,
    subscriptionPlanId: "plan-standard",
    subscriptionStatus: "active",
    viewsCount: 880,
    enquiriesCount: 43,
    bookingsCount: 12,
    createdAt: timestamp,
    updatedAt: timestamp
  },
  {
    id: "business-vryheid-quickfix-plumbing",
    ownerId: "user-owner-trade",
    businessName: "Vryheid QuickFix Plumbing",
    slug: "vryheid-quickfix-plumbing",
    description:
      "Responsive plumbing repairs, geyser replacements and leak detection for homes, rentals and small businesses.",
    shortDescription: "Plumbing repairs, geysers and maintenance.",
    logoUrl:
      "https://images.unsplash.com/photo-1621905252507-b35492cc74b4?auto=format&fit=crop&w=400&q=80",
    coverImageUrl:
      "https://images.unsplash.com/photo-1581578731548-c64695cc6952?auto=format&fit=crop&w=1400&q=80",
    galleryUrls: [
      "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&w=800&q=80"
    ],
    categoryId: "category-plumbing",
    subcategory: "Maintenance",
    tags: ["plumbing", "geysers", "emergency", "leaks"],
    phone: "+27831230004",
    whatsappNumber: "+27831230004",
    email: "support@quickfixplumbing.co.za",
    website: "",
    socialLinks: {},
    addressLine1: "6 Bhekuzulu Avenue",
    addressLine2: "",
    suburb: "Bhekuzulu",
    townId: "town-vryheid",
    province: "KwaZulu-Natal",
    country: "South Africa",
    geo: { lat: -27.7858, lng: 30.7896 },
    servicesEnabled: true,
    productsEnabled: false,
    bookingsEnabled: true,
    paymentsEnabled: false,
    deliveryEnabled: false,
    pickupEnabled: false,
    operatingHours: weekdayHours,
    priceRange: "R-RR",
    verificationStatus: "pending",
    listingStatus: "active",
    featured: false,
    featuredUntil: "",
    leadFlowType: "whatsapp_first",
    allowInstantWhatsAppLead: true,
    whatsappPrefillTemplate: "Hi, I found QuickFix Plumbing on TownConnect and need urgent help.",
    sponsoredStatus: "none",
    priorityScore: 6,
    agentId: "agent-kzn-001",
    referralCode: "PLUMB-VRY-01",
    onboardingSource: "referral",
    averageRating: 4.3,
    reviewCount: 9,
    subscriptionPlanId: "plan-free",
    subscriptionStatus: "trial",
    viewsCount: 462,
    enquiriesCount: 21,
    bookingsCount: 8,
    createdAt: timestamp,
    updatedAt: timestamp
  },
  {
    id: "business-ilanga-electrical-services",
    ownerId: "user-owner-trade",
    businessName: "iLanga Electrical Services",
    slug: "ilanga-electrical-services",
    description:
      "Certified electrical installations, prepaid meter setups, fault finding and backup power support for homes and retail spaces.",
    shortDescription: "Electrical installations and power solutions.",
    logoUrl:
      "https://images.unsplash.com/photo-1621905251918-48416bd8575a?auto=format&fit=crop&w=400&q=80",
    coverImageUrl:
      "https://images.unsplash.com/photo-1517048676732-d65bc937f952?auto=format&fit=crop&w=1400&q=80",
    galleryUrls: [
      "https://images.unsplash.com/photo-1621905252472-e5c2b88ea7d1?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1581093458791-9f3c3900d67b?auto=format&fit=crop&w=800&q=80"
    ],
    categoryId: "category-electrical",
    subcategory: "Electrical Contractor",
    tags: ["solar ready", "fault finding", "prepaid", "certified"],
    phone: "+27831230005",
    whatsappNumber: "+27831230005",
    email: "jobs@ilangaelectric.co.za",
    website: "",
    socialLinks: {
      facebook: "https://facebook.com/ilangaelectric"
    },
    addressLine1: "43 Mason Road",
    addressLine2: "",
    suburb: "Lakeside",
    townId: "town-vryheid",
    province: "KwaZulu-Natal",
    country: "South Africa",
    geo: { lat: -27.7649, lng: 30.8045 },
    servicesEnabled: true,
    productsEnabled: false,
    bookingsEnabled: true,
    paymentsEnabled: false,
    deliveryEnabled: false,
    pickupEnabled: false,
    operatingHours: weekdayHours,
    priceRange: "RR",
    verificationStatus: "verified",
    listingStatus: "active",
    featured: false,
    featuredUntil: "",
    leadFlowType: "hybrid",
    allowInstantWhatsAppLead: true,
    whatsappPrefillTemplate: "Hi, I found iLanga Electrical Services on TownConnect and need electrical assistance.",
    sponsoredStatus: "eligible",
    priorityScore: 15,
    agentId: "agent-kzn-001",
    referralCode: "ELEC-VRY-01",
    onboardingSource: "agent",
    averageRating: 4.7,
    reviewCount: 18,
    subscriptionPlanId: "plan-standard",
    subscriptionStatus: "active",
    viewsCount: 702,
    enquiriesCount: 33,
    bookingsCount: 14,
    createdAt: timestamp,
    updatedAt: timestamp
  },
  {
    id: "business-mzansi-print-hub",
    ownerId: "user-owner-food",
    businessName: "Mzansi Print Hub",
    slug: "mzansi-print-hub",
    description:
      "Affordable branding, flyers, business cards, banners and school print jobs with quick turnarounds for local businesses and events.",
    shortDescription: "Printing, signage and branding support.",
    logoUrl:
      "https://images.unsplash.com/photo-1563986768609-322da13575f3?auto=format&fit=crop&w=400&q=80",
    coverImageUrl:
      "https://images.unsplash.com/photo-1562564055-71e051d33c19?auto=format&fit=crop&w=1400&q=80",
    galleryUrls: [
      "https://images.unsplash.com/photo-1504384308090-c894fdcc538d?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1545239351-1141bd82e8a6?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1557683316-973673baf926?auto=format&fit=crop&w=800&q=80"
    ],
    categoryId: "category-printing",
    subcategory: "Print & Signage",
    tags: ["business cards", "flyers", "banners", "branding"],
    phone: "+27831230006",
    whatsappNumber: "+27831230006",
    email: "print@mzansihub.co.za",
    website: "",
    socialLinks: {
      instagram: "https://instagram.com/mzansiprinthub"
    },
    addressLine1: "55 Mark Street",
    addressLine2: "",
    suburb: "Vryheid Central",
    townId: "town-vryheid",
    province: "KwaZulu-Natal",
    country: "South Africa",
    geo: { lat: -27.7684, lng: 30.7924 },
    servicesEnabled: true,
    productsEnabled: true,
    bookingsEnabled: true,
    paymentsEnabled: false,
    deliveryEnabled: true,
    pickupEnabled: true,
    operatingHours: weekdayHours,
    priceRange: "R-RR",
    verificationStatus: "verified",
    listingStatus: "active",
    featured: true,
    featuredUntil: "2026-05-31T00:00:00.000Z",
    leadFlowType: "whatsapp_first",
    allowInstantWhatsAppLead: true,
    whatsappPrefillTemplate: "Hi, I found Mzansi Print Hub on TownConnect and need a print quote.",
    sponsoredStatus: "active",
    sponsoredPlacement: "search_spotlight",
    sponsoredUntil: "2026-05-31T00:00:00.000Z",
    sponsoredCampaignId: "campaign-print-boost-q2",
    priorityScore: 34,
    bannerCreditsUsed: 2,
    agentId: "agent-kzn-001",
    referralCode: "PRINT-VRY-01",
    onboardingSource: "agent",
    averageRating: 4.5,
    reviewCount: 24,
    subscriptionPlanId: "plan-premium",
    subscriptionStatus: "active",
    viewsCount: 1342,
    enquiriesCount: 57,
    bookingsCount: 16,
    createdAt: timestamp,
    updatedAt: timestamp
  },
  {
    id: "business-thula-car-care",
    ownerId: "user-owner-trade",
    businessName: "Thula Car Care",
    slug: "thula-car-care",
    description:
      "Vehicle servicing, diagnostics and mobile call-outs for families, taxis and fleet owners around Vryheid.",
    shortDescription: "Mechanic, diagnostics and car care services.",
    logoUrl:
      "https://images.unsplash.com/photo-1486006920555-c77dcf18193c?auto=format&fit=crop&w=400&q=80",
    coverImageUrl:
      "https://images.unsplash.com/photo-1487754180451-c456f719a1fc?auto=format&fit=crop&w=1400&q=80",
    galleryUrls: [
      "https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?auto=format&fit=crop&w=800&q=80"
    ],
    categoryId: "category-car-services",
    subcategory: "Mechanic",
    tags: ["service", "diagnostics", "mobile", "fleet"],
    phone: "+27831230007",
    whatsappNumber: "+27831230007",
    email: "service@thulacarcare.co.za",
    website: "",
    socialLinks: {},
    addressLine1: "17 Landdrost Street",
    addressLine2: "",
    suburb: "Vryheid East",
    townId: "town-vryheid",
    province: "KwaZulu-Natal",
    country: "South Africa",
    geo: { lat: -27.7729, lng: 30.7999 },
    servicesEnabled: true,
    productsEnabled: false,
    bookingsEnabled: true,
    paymentsEnabled: false,
    deliveryEnabled: false,
    pickupEnabled: false,
    operatingHours: weekdayHours,
    priceRange: "RR",
    verificationStatus: "verified",
    listingStatus: "active",
    featured: false,
    featuredUntil: "",
    leadFlowType: "hybrid",
    allowInstantWhatsAppLead: true,
    sponsoredStatus: "eligible",
    priorityScore: 12,
    referralCode: "AUTO-VRY-01",
    onboardingSource: "referral",
    averageRating: 4.4,
    reviewCount: 15,
    subscriptionPlanId: "plan-standard",
    subscriptionStatus: "active",
    viewsCount: 593,
    enquiriesCount: 25,
    bookingsCount: 11,
    createdAt: timestamp,
    updatedAt: timestamp
  },
  {
    id: "business-cedar-lodge-vryheid",
    ownerId: "user-owner-food",
    businessName: "Cedar Lodge Vryheid",
    slug: "cedar-lodge-vryheid",
    description:
      "Comfortable short-stay accommodation with secure parking, breakfast options and direct booking enquiries for travellers and business guests.",
    shortDescription: "Short-stay accommodation with direct bookings.",
    logoUrl:
      "https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=400&q=80",
    coverImageUrl:
      "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=1400&q=80",
    galleryUrls: [
      "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1512918728675-ed5a9ecdebfd?auto=format&fit=crop&w=800&q=80"
    ],
    categoryId: "category-accommodation",
    subcategory: "Guest Lodge",
    tags: ["rooms", "secure parking", "family stay", "business travel"],
    phone: "+27831230008",
    whatsappNumber: "+27831230008",
    email: "stay@cedarlodge.co.za",
    website: "",
    socialLinks: {
      facebook: "https://facebook.com/cedarlodgevryheid"
    },
    addressLine1: "2 Utrecht Road",
    addressLine2: "",
    suburb: "Vryheid North",
    townId: "town-vryheid",
    province: "KwaZulu-Natal",
    country: "South Africa",
    geo: { lat: -27.7607, lng: 30.7983 },
    servicesEnabled: true,
    productsEnabled: false,
    bookingsEnabled: true,
    paymentsEnabled: false,
    deliveryEnabled: false,
    pickupEnabled: false,
    operatingHours: hospitalityHours,
    priceRange: "RR-RRR",
    verificationStatus: "verified",
    listingStatus: "active",
    featured: false,
    featuredUntil: "",
    leadFlowType: "whatsapp_first",
    allowInstantWhatsAppLead: true,
    sponsoredStatus: "active",
    sponsoredPlacement: "town_priority",
    sponsoredUntil: "2026-06-15T00:00:00.000Z",
    priorityScore: 30,
    referralCode: "LODGE-VRY-01",
    onboardingSource: "organic",
    averageRating: 4.7,
    reviewCount: 31,
    subscriptionPlanId: "plan-premium",
    subscriptionStatus: "active",
    viewsCount: 1199,
    enquiriesCount: 61,
    bookingsCount: 22,
    createdAt: timestamp,
    updatedAt: timestamp
  }
];

export const services: Service[] = [
  {
    id: "service-burger-combo-catering",
    businessId: "business-vryheid-grill-house",
    title: "Burger Combo Catering",
    slug: "burger-combo-catering",
    description: "Bulk burger and chips combos for school, church and family events.",
    price: 1200,
    currency: "ZAR",
    durationMinutes: 120,
    isActive: true,
    createdAt: timestamp,
    updatedAt: timestamp
  },
  {
    id: "service-weekend-platter-order",
    businessId: "business-vryheid-grill-house",
    title: "Weekend Platter Order",
    slug: "weekend-platter-order",
    description: "Pre-order chicken, braai and sides platters for pickup or delivery.",
    price: 650,
    currency: "ZAR",
    durationMinutes: 60,
    isActive: true,
    createdAt: timestamp,
    updatedAt: timestamp
  },
  {
    id: "service-classic-gel-set",
    businessId: "business-glow-beauty-studio",
    title: "Classic Gel Set",
    slug: "classic-gel-set",
    description: "Full gel manicure set with basic nail art.",
    price: 250,
    currency: "ZAR",
    durationMinutes: 90,
    isActive: true,
    createdAt: timestamp,
    updatedAt: timestamp
  },
  {
    id: "service-bridal-makeup",
    businessId: "business-glow-beauty-studio",
    title: "Bridal Makeup Trial",
    slug: "bridal-makeup-trial",
    description: "Consultation and bridal look preview for wedding clients.",
    price: 700,
    currency: "ZAR",
    durationMinutes: 120,
    isActive: true,
    createdAt: timestamp,
    updatedAt: timestamp
  },
  {
    id: "service-home-renovation-quote",
    businessId: "business-amajuba-buildworks",
    title: "Home Renovation Site Visit",
    slug: "home-renovation-site-visit",
    description: "On-site assessment and project quotation for renovations.",
    price: 450,
    currency: "ZAR",
    durationMinutes: 90,
    isActive: true,
    createdAt: timestamp,
    updatedAt: timestamp
  },
  {
    id: "service-geyser-replacement",
    businessId: "business-vryheid-quickfix-plumbing",
    title: "Geyser Replacement Assessment",
    slug: "geyser-replacement-assessment",
    description: "Inspection, sizing and replacement quote for geyser jobs.",
    price: 350,
    currency: "ZAR",
    durationMinutes: 60,
    isActive: true,
    createdAt: timestamp,
    updatedAt: timestamp
  },
  {
    id: "service-prepaid-meter-install",
    businessId: "business-ilanga-electrical-services",
    title: "Prepaid Meter Installation",
    slug: "prepaid-meter-installation",
    description: "Residential prepaid meter installation and compliance checks.",
    price: 1500,
    currency: "ZAR",
    durationMinutes: 180,
    isActive: true,
    createdAt: timestamp,
    updatedAt: timestamp
  },
  {
    id: "service-flyer-design-print",
    businessId: "business-mzansi-print-hub",
    title: "Flyer Design and Print",
    slug: "flyer-design-and-print",
    description: "100 full-colour A5 flyers with basic layout design included.",
    price: 480,
    currency: "ZAR",
    durationMinutes: 1440,
    isActive: true,
    createdAt: timestamp,
    updatedAt: timestamp
  },
  {
    id: "service-business-card-print",
    businessId: "business-mzansi-print-hub",
    title: "Business Card Print Run",
    slug: "business-card-print-run",
    description: "250 laminated business cards for small businesses.",
    price: 350,
    currency: "ZAR",
    durationMinutes: 1440,
    isActive: true,
    createdAt: timestamp,
    updatedAt: timestamp
  },
  {
    id: "service-minor-car-service",
    businessId: "business-thula-car-care",
    title: "Minor Car Service",
    slug: "minor-car-service",
    description: "Oil, filters and key vehicle checks for everyday cars.",
    price: 950,
    currency: "ZAR",
    durationMinutes: 150,
    isActive: true,
    createdAt: timestamp,
    updatedAt: timestamp
  },
  {
    id: "service-room-booking",
    businessId: "business-cedar-lodge-vryheid",
    title: "Standard Room Booking",
    slug: "standard-room-booking",
    description: "Direct booking request for a standard en-suite room.",
    price: 850,
    currency: "ZAR",
    durationMinutes: 30,
    isActive: true,
    createdAt: timestamp,
    updatedAt: timestamp
  }
];

export const products: Product[] = [
  {
    id: "product-family-braai-pack",
    businessId: "business-vryheid-grill-house",
    title: "Family Braai Pack",
    slug: "family-braai-pack",
    description: "Ready-to-share braai pack with meat, pap and salads.",
    price: 420,
    currency: "ZAR",
    imageUrl:
      "https://images.unsplash.com/photo-1529193591184-b1d58069ecdd?auto=format&fit=crop&w=800&q=80",
    stockStatus: "in_stock",
    sku: "VGH-BRAAI-001",
    isActive: true,
    createdAt: timestamp,
    updatedAt: timestamp
  },
  {
    id: "product-lash-aftercare-kit",
    businessId: "business-glow-beauty-studio",
    title: "Lash Aftercare Kit",
    slug: "lash-aftercare-kit",
    description: "Foam cleanser and mini brush for lash clients.",
    price: 130,
    currency: "ZAR",
    imageUrl:
      "https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?auto=format&fit=crop&w=800&q=80",
    stockStatus: "low_stock",
    sku: "GBS-LASH-001",
    isActive: true,
    createdAt: timestamp,
    updatedAt: timestamp
  },
  {
    id: "product-business-card-pack",
    businessId: "business-mzansi-print-hub",
    title: "250 Business Cards",
    slug: "250-business-cards",
    description: "Full-colour laminated business cards for startups and local shops.",
    price: 350,
    currency: "ZAR",
    imageUrl:
      "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=800&q=80",
    stockStatus: "in_stock",
    sku: "MPH-CARD-250",
    isActive: true,
    createdAt: timestamp,
    updatedAt: timestamp
  },
  {
    id: "product-pullup-banner",
    businessId: "business-mzansi-print-hub",
    title: "Pull-Up Banner",
    slug: "pull-up-banner",
    description: "One branded pull-up banner for events, expos and storefronts.",
    price: 900,
    currency: "ZAR",
    imageUrl:
      "https://images.unsplash.com/photo-1504384308090-c894fdcc538d?auto=format&fit=crop&w=800&q=80",
    stockStatus: "in_stock",
    sku: "MPH-BANNER-001",
    isActive: true,
    createdAt: timestamp,
    updatedAt: timestamp
  }
];

export const bookings: Booking[] = [
  {
    id: "booking-001",
    businessId: "business-glow-beauty-studio",
    serviceId: "service-classic-gel-set",
    customerId: "user-customer",
    customerName: "Lerato Mthembu",
    customerEmail: "customer@townconnect.co.za",
    customerPhone: "+27830000002",
    customerWhatsappNumber: "+27830000002",
    requestedDate: "2026-04-02",
    requestedTime: "10:00",
    notes: "Prefer neutral colours for a work event.",
    leadChannel: "whatsapp",
    leadIntent: "booking",
    leadSource: "organic",
    referralCode: "GLOW-VRY-01",
    agentId: "agent-kzn-002",
    status: "pending",
    createdAt: timestamp,
    updatedAt: timestamp
  },
  {
    id: "booking-002",
    businessId: "business-vryheid-grill-house",
    serviceId: "service-weekend-platter-order",
    customerId: "user-customer",
    customerName: "Lerato Mthembu",
    customerEmail: "customer@townconnect.co.za",
    customerPhone: "+27830000002",
    customerWhatsappNumber: "+27830000002",
    requestedDate: "2026-04-05",
    requestedTime: "13:00",
    notes: "Platter for 15 people, pickup please.",
    leadChannel: "whatsapp",
    leadIntent: "booking",
    leadSource: "referral",
    referralCode: "GRILL-VRY-01",
    agentId: "agent-kzn-001",
    status: "accepted",
    createdAt: timestamp,
    updatedAt: timestamp
  },
  {
    id: "booking-003",
    businessId: "business-thula-car-care",
    serviceId: "service-minor-car-service",
    customerId: "user-customer",
    customerName: "Lerato Mthembu",
    customerEmail: "customer@townconnect.co.za",
    customerPhone: "+27830000002",
    customerWhatsappNumber: "+27830000002",
    requestedDate: "2026-04-03",
    requestedTime: "08:30",
    notes: "Toyota Corolla 2018.",
    leadChannel: "form",
    leadIntent: "booking",
    leadSource: "organic",
    referralCode: "AUTO-VRY-01",
    status: "completed",
    createdAt: timestamp,
    updatedAt: timestamp
  }
];

export const enquiries: Enquiry[] = [
  {
    id: "enquiry-001",
    businessId: "business-amajuba-buildworks",
    customerId: "user-customer",
    name: "Lerato Mthembu",
    email: "customer@townconnect.co.za",
    phone: "+27830000002",
    whatsappNumber: "+27830000002",
    subject: "Kitchen renovation quote",
    message: "I need a quote for cabinets, tiling and a full repaint for a small kitchen.",
    relatedType: "general",
    relatedId: "",
    leadChannel: "whatsapp",
    leadIntent: "quote",
    leadSource: "organic",
    preferredContactChannel: "whatsapp",
    referralCode: "BUILD-VRY-01",
    agentId: "agent-kzn-001",
    status: "new",
    createdAt: timestamp,
    updatedAt: timestamp
  },
  {
    id: "enquiry-002",
    businessId: "business-mzansi-print-hub",
    customerId: "user-customer",
    name: "Lerato Mthembu",
    email: "customer@townconnect.co.za",
    phone: "+27830000002",
    whatsappNumber: "+27830000002",
    subject: "School event banners",
    message: "Need 3 pull-up banners and 100 flyers for a school event next week.",
    relatedType: "product",
    relatedId: "product-pullup-banner",
    leadChannel: "whatsapp",
    leadIntent: "order",
    leadSource: "sponsored",
    preferredContactChannel: "whatsapp",
    referralCode: "PRINT-VRY-01",
    agentId: "agent-kzn-001",
    status: "responded",
    createdAt: timestamp,
    updatedAt: timestamp
  },
  {
    id: "enquiry-003",
    businessId: "business-cedar-lodge-vryheid",
    name: "Nomusa Zulu",
    email: "nomusa@example.com",
    phone: "+27834445555",
    whatsappNumber: "+27834445555",
    subject: "Weekend accommodation",
    message: "Do you have 2 rooms available for 18 April for a family stay?",
    relatedType: "service",
    relatedId: "service-room-booking",
    leadChannel: "whatsapp",
    leadIntent: "booking",
    leadSource: "banner",
    preferredContactChannel: "whatsapp",
    referralCode: "LODGE-VRY-01",
    status: "read",
    createdAt: timestamp,
    updatedAt: timestamp
  }
];

export const subscriptions: Subscription[] = [
  {
    id: "sub-001",
    businessId: "business-vryheid-grill-house",
    planId: "plan-standard",
    planName: "standard",
    status: "active",
    billingCycle: "monthly",
    amount: 299,
    currency: "ZAR",
    startsAt: "2026-03-01T00:00:00.000Z",
    endsAt: "2026-03-31T23:59:59.000Z",
    paymentProvider: "placeholder",
    providerSlug: "placeholder",
    paymentStatus: "mocked",
    paymentIntentId: "pi-standard-001",
    agentId: "agent-kzn-001",
    referralCode: "GRILL-VRY-01",
    paymentReference: "STD-001",
    createdAt: timestamp,
    updatedAt: timestamp
  },
  {
    id: "sub-002",
    businessId: "business-glow-beauty-studio",
    planId: "plan-premium",
    planName: "premium",
    status: "active",
    billingCycle: "monthly",
    amount: 699,
    currency: "ZAR",
    startsAt: "2026-03-10T00:00:00.000Z",
    endsAt: "2026-04-10T23:59:59.000Z",
    paymentProvider: "placeholder",
    providerSlug: "placeholder",
    paymentStatus: "mocked",
    paymentIntentId: "pi-premium-002",
    agentId: "agent-kzn-002",
    referralCode: "GLOW-VRY-01",
    paymentReference: "PREM-002",
    createdAt: timestamp,
    updatedAt: timestamp
  },
  {
    id: "sub-003",
    businessId: "business-vryheid-quickfix-plumbing",
    planId: "plan-free",
    planName: "free",
    status: "trial",
    billingCycle: "monthly",
    amount: 0,
    currency: "ZAR",
    startsAt: "2026-03-20T00:00:00.000Z",
    endsAt: "2026-04-20T23:59:59.000Z",
    paymentProvider: "placeholder",
    providerSlug: "placeholder",
    paymentStatus: "mocked",
    paymentIntentId: "pi-free-003",
    agentId: "agent-kzn-001",
    referralCode: "PLUMB-VRY-01",
    paymentReference: "FREE-003",
    createdAt: timestamp,
    updatedAt: timestamp
  }
];

export const plans: Plan[] = [
  {
    id: "plan-free",
    name: "Free",
    slug: "free",
    price: 0,
    billingCycle: "monthly",
    description: planDefinitions[0].description,
    ctaLabel: planDefinitions[0].ctaLabel,
    features: planDefinitions[0].features,
    config: planDefinitions[0].limits,
    isActive: true,
    sortOrder: 1,
    createdAt: timestamp,
    updatedAt: timestamp
  },
  {
    id: "plan-standard",
    name: "Standard",
    slug: "standard",
    price: 299,
    billingCycle: "monthly",
    description: planDefinitions[1].description,
    highlightLabel: planDefinitions[1].highlightLabel,
    ctaLabel: planDefinitions[1].ctaLabel,
    recommended: true,
    features: planDefinitions[1].features,
    config: planDefinitions[1].limits,
    isActive: true,
    sortOrder: 2,
    createdAt: timestamp,
    updatedAt: timestamp
  },
  {
    id: "plan-premium",
    name: "Premium",
    slug: "premium",
    price: 699,
    billingCycle: "monthly",
    description: planDefinitions[2].description,
    highlightLabel: planDefinitions[2].highlightLabel,
    ctaLabel: planDefinitions[2].ctaLabel,
    features: planDefinitions[2].features,
    config: planDefinitions[2].limits,
    isActive: true,
    sortOrder: 3,
    createdAt: timestamp,
    updatedAt: timestamp
  }
];

export const reviews: Review[] = [
  {
    id: "review-001",
    businessId: "business-glow-beauty-studio",
    customerId: "user-customer",
    rating: 5,
    title: "Always polished",
    comment: "Fast booking, great service and very clean studio.",
    status: "approved",
    createdAt: timestamp,
    updatedAt: timestamp
  },
  {
    id: "review-002",
    businessId: "business-vryheid-grill-house",
    customerId: "user-customer",
    rating: 4,
    title: "Great platters",
    comment: "The platter portions were generous and pickup was easy.",
    status: "approved",
    createdAt: timestamp,
    updatedAt: timestamp
  }
];

export const banners: Banner[] = [
  {
    id: "banner-home-001",
    title: "Support local businesses in Vryheid",
    imageUrl:
      "https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=1200&q=80",
    linkUrl: "/list-your-business",
    placement: "home_top",
    description: "Launch your TownConnect profile and start capturing local demand.",
    ctaLabel: "List now",
    campaignType: "subscription",
    priority: 5,
    isActive: true,
    startDate: "2026-03-01T00:00:00.000Z",
    endDate: "2026-06-30T00:00:00.000Z",
    createdAt: timestamp,
    updatedAt: timestamp
  },
  {
    id: "banner-town-001",
    title: "Premium listings available for featured placement",
    imageUrl:
      "https://images.unsplash.com/photo-1521737604893-d14cc237f11d?auto=format&fit=crop&w=1200&q=80",
    linkUrl: "/pricing",
    placement: "town",
    description: "Upgrade for stronger visibility and admin-managed featured placement.",
    ctaLabel: "See plans",
    campaignType: "promotion",
    townId: "town-vryheid",
    priority: 4,
    isActive: true,
    startDate: "2026-03-01T00:00:00.000Z",
    endDate: "2026-06-30T00:00:00.000Z",
    createdAt: timestamp,
    updatedAt: timestamp
  },
  {
    id: "banner-search-001",
    title: "Glow Beauty Studio Spring Campaign",
    imageUrl:
      "https://images.unsplash.com/photo-1512496015851-a90fb38ba796?auto=format&fit=crop&w=1200&q=80",
    linkUrl: "/business/glow-beauty-studio",
    placement: "search_top",
    description: "Sponsored discovery campaign for premium business visibility.",
    ctaLabel: "Book now",
    campaignType: "sponsored_business",
    sponsorBusinessId: "business-glow-beauty-studio",
    categoryId: "category-beauty",
    priority: 8,
    isActive: true,
    startDate: "2026-03-01T00:00:00.000Z",
    endDate: "2026-06-30T00:00:00.000Z",
    createdAt: timestamp,
    updatedAt: timestamp
  }
];

export const platformSettings: PlatformSettings[] = [
  {
    id: "platform-main",
    currency: "ZAR",
    defaultCountry: "South Africa",
    supportedProvinces: ["KwaZulu-Natal"],
    featuredBusinessLimit: 6,
    sponsoredListingLimit: 4,
    allowSelfSignup: true,
    allowFreePlan: true,
    allowSponsoredListings: true,
    contactEmail: "hello@townconnect.co.za",
    whatsappSupport: "+27831234567",
    leadFlowDefault: "whatsapp_first",
    supportedPaymentProviders: [...SUPPORTED_PAYMENT_PROVIDERS],
    featuredEligibilityRequiresVerification: true,
    referralProgramEnabled: true,
    agentCommissionEnabled: true,
    updatedAt: timestamp
  }
];

export const activityLogs: ActivityLog[] = [
  {
    id: "activity-001",
    actorId: "user-admin",
    actorRole: "admin",
    entityType: "business",
    entityId: "business-glow-beauty-studio",
    action: "featured_listing_enabled",
    metadata: { placement: "home_top" },
    createdAt: timestamp
  },
  {
    id: "activity-002",
    actorId: "user-admin",
    actorRole: "admin",
    entityType: "business",
    entityId: "business-vryheid-quickfix-plumbing",
    action: "verification_pending_review",
    metadata: { listingStatus: "active" },
    createdAt: timestamp
  },
  {
    id: "activity-003",
    actorId: "user-owner-food",
    actorRole: "business_owner",
    entityType: "service",
    entityId: "service-weekend-platter-order",
    action: "service_updated",
    metadata: { price: 650 },
    createdAt: timestamp
  }
];

export const seedCollections = {
  users,
  businesses,
  towns,
  categories,
  services,
  products,
  bookings,
  enquiries,
  subscriptions,
  plans,
  reviews,
  banners,
  platform_settings: platformSettings,
  activity_logs: activityLogs
};

export const seedData = {
  towns,
  categories,
  users,
  businesses,
  services,
  products,
  bookings,
  enquiries,
  subscriptions,
  plans,
  reviews,
  banners,
  platformSettings,
  activityLogs
};
